-- 기존에 있는 테이블이라면, 삭제
DROP TABLE GALLERY_BOARD;

-- 회원 테이블 생성
CREATE TABLE GALLERY_BOARD 
(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(32) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(4000),
    POSTDATE DATE NOT NULL,
    LASTDATE DATE NOT NULL,
    IP VARCHAR2(100) NOT NULL,
    HIT NUMBER NOT NULL,
    IMAGENAME VARCHAR2(4000)
);

-- 회원 시퀀스 생성
DROP SEQUENCE GALLERY_BOARD_SEQ;
CREATE SEQUENCE GALLERY_BOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

-- FOREIGN
ALTER TABLE GALLERY_BOARD ADD CONSTRAINT GALLERY_MEMBER_FK FOREIGN KEY(ID) REFERENCES MEMBER(ID);




