-- 기존에 있는 테이블이라면, 삭제
DROP TABLE REPLY;

-- 댓글 테이블 생성
CREATE TABLE REPLY
(
	NO NUMBER PRIMARY KEY,
	GALLERY_NO NUMBER NOT NULL,
	ID VARCHAR2(32) NOT NULL,
	CONTENT VARCHAR2(1000),
    POSTDATE DATE NOT NULL,
    IP VARCHAR2(100) NOT NULL
);

-- 댓글 시퀀스 생성
DROP SEQUENCE REPLY_SEQ;
CREATE SEQUENCE REPLY_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

-- FOREIGN
ALTER TABLE REPLY ADD CONSTRAINT REPLY_MEMBER_FK FOREIGN KEY(ID) REFERENCES MEMBER(ID);
ALTER TABLE REPLY ADD CONSTRAINT REPLY_GALLERY_FK FOREIGN KEY(GALLERY_NO) REFERENCES GALLERY_BOARD(NO);




