DROP TABLE BOARD;
CREATE TABLE BOARD
(
	NO NUMBER PRIMARY KEY,
	WRITER VARCHAR2(32),
	TITLE VARCHAR2(32),
	CONTENT VARCHAR2(32),
	POSTDATE DATE
);

INSERT INTO BOARD VALUES (1, '관리자', '공지사항', '공지입니다.', SYSDATE);
INSERT INTO BOARD VALUES (2, '운영자', '요청사항', '요청입니다.', SYSDATE);
INSERT INTO BOARD VALUES (3, '당직자', '협조사항', '협조입니다.', SYSDATE);
INSERT INTO BOARD VALUES (4, '운영자', '필동사항', '필독입니다.', SYSDATE);
INSERT INTO BOARD VALUES (5, '관리자', '요구사항', '요구입니다.', SYSDATE);
COMMIT
