DROP TABLE MEMBER;
CREATE TABLE MEMBER
(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(32) NOT NULL UNIQUE,
	NAME VARCHAR2(64),
	ADDRESS VARCHAR2(100),
	GENDER VARCHAR2(10)
);

DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

select * from member;

INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'admin', '관리자', '서울', '남');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user1', '사용자1', '서울', '남');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user2', '사용자2', '서울', '여');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user3', '사용자3', '서울', '남');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user4', '사용자4', '서울', '여');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user5', '사용자5', '서울', '여');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user6', '사용자6', '서울', '여');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user7', '사용자7', '서울', '남');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user8', '사용자8', '서울', '남');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user9', '사용자9', '서울', '남');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user10', '사용자10', '서울', '남');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user11', '사용자11', '서울', '남');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user12', '사용자12', '서울', '남');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user13', '사용자13', '서울', '남');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user14', '사용자14', '서울', '남');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user15', '사용자15', '서울', '남');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user16', '사용자16', '서울', '남');
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'user17', '사용자17', '서울', '남');
COMMIT;